name: primedehealth
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  dio_smart_retry: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.2.0
  gap: ^3.0.0
  get_it: ^7.6.4
  http: ^1.1.0
  injectable: ^1.5.3
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^1.4.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  retrofit: ^4.0.1
  retry: ^3.1.2
  device_preview: ^1.2.0
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  injectable_generator: ^1.5.3
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1+1
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  http: ^1.0.0
  intl: ^0.17.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/Aeonik-Air.otf
        - asset: assets/fonts/Aeonik-AirItalic.otf
          style: italic
        - asset: assets/fonts/Aeonik-Black.otf
        - asset: assets/fonts/Aeonik-BlackItalic.otf
          style: italic
        - asset: assets/fonts/Aeonik-Bold.otf
          weight: 700
        - asset: assets/fonts/Aeonik-BoldItalic.otf
          style: italic
        - asset: assets/fonts/Aeonik-Light.otf
        - asset: assets/fonts/Aeonik-LightItalic.otf
          style: italic
        - asset: assets/fonts/Aeonik-Medium.otf
          weight: 500
        - asset: assets/fonts/Aeonik-MediumItalic.otf
          style: italic
        - asset: assets/fonts/Aeonik-Regular.otf
        - asset: assets/fonts/Aeonik-RegularItalic.otf
          style: italic
        - asset: assets/fonts/Aeonik-Thin.otf
        - asset: assets/fonts/Aeonik-ThinItalic.otf
          style: italic
